---
build_from:
  aarch64: ghcr.io/hassio-addons/base:latest
  amd64: ghcr.io/hassio-addons/base:latest
  armhf: ghcr.io/hassio-addons/base-armhf:latest
  armv7: ghcr.io/hassio-addons/base-armv7:latest
  i386: ghcr.io/hassio-addons/base-i386:latest

labels:
  org.opencontainers.image.title: "SCP Backup"
  org.opencontainers.image.description: "Backup Home Assistant to a remote server via SCP"
  org.opencontainers.image.source: "https://github.com/pagubg/ha-addons"
  org.opencontainers.image.authors: "HA Addon Developer"
  org.opencontainers.image.licenses: "Apache-2.0"
