---
build_from:
  aarch64: ghcr.io/hassio-addons/base:latest
  amd64: ghcr.io/hassio-addons/base:latest

labels:
  org.opencontainers.image.title: "SCP Backup"
  org.opencontainers.image.description: "Backup Home Assistant to a remote server via SCP"
  org.opencontainers.image.source: "https://github.com/pagubg/ha-addons"
  org.opencontainers.image.authors: "pagubg"
  org.opencontainers.image.licenses: "Apache-2.0"
